<testsuite name="Django Project Tests" errors="2" failures="0" skips="0" tests="2" time="0.000"><testcase time="0.000024" classname="unittest.loader._FailedTest" name="—"><error type="builtins.ImportError" message="Failed to import test module: —&#10;Traceback (most recent call last):&#10;  File &quot;/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py&quot;, line 154, in loadTestsFromName&#10;    module = __import__(module_name)&#10;ModuleNotFoundError: No module named '—'&#10;">ImportError: Failed to import test module: —
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named '—'

</error></testcase><testcase time="0.000012" classname="unittest.loader._FailedTest" name="enable-coverage"><error type="builtins.ImportError" message="Failed to import test module: enable-coverage&#10;Traceback (most recent call last):&#10;  File &quot;/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py&quot;, line 154, in loadTestsFromName&#10;    module = __import__(module_name)&#10;ModuleNotFoundError: No module named 'enable-coverage'&#10;">ImportError: Failed to import test module: enable-coverage
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'enable-coverage'

</error></testcase></testsuite>